### ISSUE TITLE
The pom file is broken

### ISSUE THREAD

**Issue by RadekManak** [pmikova/Java-Runtime-Decompiler#1]
com.sun.tools is missing in maven central.

The current workaround I'm using is to add tools.jar manually into my local maven repo.

Possible solution is to upgrade to java 9-10. And exclude com.sun.tools from pom.xml file.

**Comment by judovana** [comment]
Also system scope for such cases:
            <scope>system</scope>
            <systemPath>/usr/lib/jvm/java-1.8.0-openjdk/lib/tools.jar</systemPath>

**Comment by judovana** [comment]
This depndence is needed also in runtime:
java -cp /usr/lib/jvm/java-1.8.0-openjdk/lib/tools.jar:java-runtime-decompiler-1.0.0-SNAPSHOT.jar:/home/jvanek/.m2/repository/com/fifesoft/rsyntaxtextarea/2.6.1/rsyntaxtextarea-2.6.1.jar   com.redhat.thermostat.vm.decompiler.data.Main


Still the whole byteman is missing in this moment, and although program complains, no stacktrace is logged. Never, ever swallow stacktraces:)

**Comment by judovana** [comment]
Thanx!

Why the byteman bump?
