### ISSUE TITLE
Allow to have multiple class-buffers open

### ISSUE THREAD

**Issue by judovana** [pmikova/java-runtime-decompiler#109]
Continuation of #65. *Detach is cool, but the original issuer was unable to express his thoughts.*

The original idea was ability to have several classes opened at one time. It is still not possible.

Only one window should be affected by changes in classes list. 
Other detached windows should be permanently connected with the initial class, while still allowing for overwriting and decompilation with a different plugin.

**Comment by AurumTheEnd** [comment]
A precursor to this would be to associate VM + class information with(in) the buffers panel, rather than how it is currently always read from the current JList selection.

**Comment by judovana** [comment]
to much work with small gain.
JRD now alows to have notpead opened. One can copypaste both text and bianry to it, and then return it to class buffers as needed...
