### ISSUE TITLE
Improve decompiler agent logging

### ISSUE THREAD

**Issue by AurumTheEnd** [pmikova/java-runtime-decompiler#113]
Currently, errors within the agent are
 - printed to stdout/stderr of the target process
 - logged on JRD's side as a useless `"Agent returned error."` message.
 
Make agent log more detailed, informative messages, possibly along with a trace of the exception, if there is any.

**Comment by judovana** [comment]
https://github.com/pmikova/java-runtime-decompiler/pull/144

**Comment by judovana** [comment]
https://github.com/pmikova/java-runtime-decompiler/issues/143

**Comment by judovana** [comment]
done. Future work == future issue.
