### ISSUE TITLE
Overwritten class (sometines) resets to its original state

### ISSUE THREAD

**Issue by judovana** [pmikova/java-runtime-decompiler#136]
Consider casual `HelloWorld` class, which has infinite loop to print `"HELLO"`.
Sometimes, the following happens:
 - `HelloWorld` runs
 - JRD obtains its code
 - sout(`"HELLO"`) is present in the decompiled code
 - we use JRD to overwrite it to sout(`"BYE"`), and upload new code
 - the running `HelloWorld` program's output changes, and now it prints `"BYE"`
 - if we request the bytecode again, usually it contains sout(`"BYE"`), but **_sometimes_** it contains sout(`"HELLO"`)
 - in this moment, even less frequently, the `HelloWorld` will start to print `"HELLO"` again

**Comment by mkoncek** [comment]
I will inspect whether this isn't CPLC caching incorrectly.

**Comment by judovana** [comment]
nope. It is not CPLC fault. It happens also with direct binary change, or through jasm/jcoder.

**Comment by judovana** [comment]
I need to find a deterministic case.

**Comment by judovana** [comment]
Should be indirrectlky fixed by https://github.com/pmikova/java-runtime-decompiler/pull/154

**Comment by judovana** [comment]
#154 merged. cross fingers
