### ISSUE TITLE
Save bytecode before overwrite to provide local history

### ISSUE THREAD

**Issue by judovana** [pmikova/java-runtime-decompiler#141]
... and to allow roll back.

**Comment by judovana** [comment]
The gui will be providing timestamped combobox with revisions

**Comment by AurumTheEnd** [comment]
This will require a major overhaul of the way class data is kept. Currently, when fetching bytecode, the old state is discarded and a new one takes it place - overall what I would call a pretty stateless way of doing things.

#119 is on the right path for this with its ClassInfo class, but that still doesn't hold the bytecode itself. 

Implementation of #109 will also require some degree of separation/abstraction in regards to the state of bytecode.

**Comment by judovana** [comment]
I think it is quite easy to keep global hasmap<vmId,<hashmap<fqn,list<byte[]>>>  whiich will add new entry every time  uploadbytecode is called.
Then by clicking in combobox to pass the byte[] from this "cache" instead of calling agent. hmm?

**Comment by AurumTheEnd** [comment]
> keep global HashMap<VmInfo,<HashMap<fqn, List<byte[]>>

That there is the problem. Keeping a global "database" by slapping a new feature on top and not including it into the existing hierarchy of classes
 - disregards the current codebase
 - violates the object-oriented paradigm
 - would be a pain in the future to maintain

That is why I listed the related topics, moving from stateless bytecode to a stateful design is the harder, but more correct way to go.

**Comment by judovana** [comment]
Sure. Then jsut drop firs tlevel of map, and it will be part of the VmInfo

**Comment by judovana** [comment]
surpassed by #152
