### ISSUE TITLE
Global GUI console should have some keyword highlighting

### ISSUE THREAD

**Issue by judovana** [pmikova/java-runtime-decompiler#142]

**Comment by judovana** [comment]
the compilation output is very badly readable

**Comment by AurumTheEnd** [comment]
RSyntaxArea might help with this, it is bundled with some highlighters. Worth exploring, but results are not guaranteed.

**Comment by judovana** [comment]
yup. that was in my mind too.  rsyntaxTextarea have quite simple keyword deffinition. So +1!
