### ISSUE TITLE
Have more information-packed error messages than ERROR and error

### ISSUE THREAD

**Issue by judovana** [pmikova/java-runtime-decompiler#143]
Currently just "error" or "ERROR" is literally useless for tracing. Current mindset is to just start with "error" and append at least something...

**Comment by judovana** [comment]
https://github.com/pmikova/java-runtime-decompiler/pull/144

**Comment by AurumTheEnd** [comment]
How about a format of
```
ERROR\n
(eg.) IOException occured\n
at org.jrd.madeup.file:86\n
at another.trace.line:69\n
...\n
```

**Comment by judovana** [comment]
Nope. The communication agen-programm is supe rdummy. It is line based.  Right now, one line read contains all,, To have  this , much better commuication would need to go in. I would chose json now. JRD 7.0. No earlier :)

**Comment by AurumTheEnd** [comment]
While one line contains all, we already hide additional information in it, for example in the case of `getAllLoadedClassesAction`, which parses the one-line-but-delimited response. Something similar could work for errors, but I agree that it is an ugly solution.

**Comment by judovana** [comment]
single line supported.
MUltiline, or json based.. another issue, another release
