### ISSUE TITLE
before decompilation, all inner (including recursive) classes must be loaded

### ISSUE THREAD

**Issue by judovana** [pmikova/java-runtime-decompiler#157]
the parsing method is provided by CPLC

**Comment by mkoncek** [comment]
The function `ExtractTypenames.extractNested(byte[], ClassesProvider)` should do exactly that: find all nested classes (including anonymous ones) transitively.

**Comment by mkoncek** [comment]
I have one more question about the API, should i use `byte[]` for bytecode and `String` for FQN or rather our established `IdentifiedBytecode` and `ClassIdentifier`?

**Comment by judovana** [comment]
yes. I would stay at byte[] and string.
btw, is it hard to add a method, which will extract al fully qualified methods?

**Comment by mkoncek** [comment]
If you mean all **declared** methods of the outer class, that sohuld be trivial.

**Comment by judovana** [comment]
..and iner classes...


But seeying your point in binary world - yes that would be enoughr bcasue it  is esay to find inner classes, and then iterate one by one. 

//me in autocompeltion field now ;)

**Comment by judovana** [comment]
```
public class HelloWorld {
    public static void main(String[] stringArray) throws Exception {
        while (true) {
            new HelloWorld().print();
            System.out.println("Hello, World!");
            Thread.sleep(1000L);
        }
    }

    public void print() {
        System.out.println("Hello, World!");
    }

    public static class NeverUsed {
        public static Integer singleton;
    }
}
```


now works in  https://github.com/pmikova/java-runtime-decompiler/pull/163/commits/30e4954b19ea81962cf244e3fa33dac14fa47e2f

**Comment by judovana** [comment]
Its a question, whether this hsold have settins checkbox to disable it

**Comment by mkoncek** [comment]
Functions have been implemented, the outer class has been renamed to `BytecodeExtractor`.

**Comment by judovana** [comment]
for some reason nothing from above works in cli. nvm.... work in progress
Thanx!

**Comment by judovana** [comment]
my bad. cli works. It was ghost in the shelll
