### ISSUE TITLE
Injection of second agent replaces/removes the first one

### ISSUE THREAD

**Issue by judovana** [pmikova/java-runtime-decompiler#183]
a) a "new" second JRD process does not see the modifications of a previous first JRD process
b) if the second JRD is unloaded, first JRD cannot read the bytecode, until it injects the agent

**Comment by AurumTheEnd** [comment]
Is b) really true? That once again shakes up how I understood the transformation agent pipeline :/

**Comment by judovana** [comment]
#218

**Comment by judovana** [comment]
Resolvdci  8.0
