### ISSUE TITLE
add jd decompiler?

### ISSUE THREAD

**Issue by judovana** [pmikova/java-runtime-decompiler#221]
https://github.com/java-decompiler/jd-core

**Comment by mkoncek** [comment]
This thing also exists:
https://github.com/Storyyeller/Krakatau

**Comment by judovana** [comment]
wait. What have Krakatau common with JD? Afaik nothing.
And no, I'mnot going to use python java disassembel r:)

**Comment by judovana** [comment]
note, that jd-core is gradle project (without deps). but is in maven repos: https://mvnrepository.com/artifact/org.jd/jd-core/1.1.3

**Comment by judovana** [comment]
done. But is of poor quality
