### ISSUE TITLE
Exclude lambdas and array types from the list of loaded classes in GUI

### ISSUE THREAD

**Issue by mkoncek** [pmikova/java-runtime-decompiler#224]
Neither lambdas nor array types are real types and if you attempt to load their bytecode, it fails.
There probably is no information value in knowing they have been loaded (maybe i am wrong).
In any case the filter is very simple:
1) If the type name starts with `[`, it is an array type
2) If the type contains a `/`, it is a lambda type.

**Comment by judovana** [comment]
afaik all those are corrctly sorted to thebottom. At least in gui. It will reamin like that. not removing them
