### ISSUE TITLE
please provide javap support

### ISSUE THREAD

**Issue by judovana** [pmikova/java-runtime-decompiler#23]
java -cp $JAVA_HOME/lib/tools.jar com.sun.tools.javap.Main YourTestClass

**Comment by judovana** [comment]
I wonted to pipe to javap from the CLI i'mdoing, and  realized... now donot laugh...javap do not eat std in and (in addition) compalinsabout process substitution....

**Comment by judovana** [comment]
basic support for javap  added to CLI. Any voulnteer for GUI?-)

**Comment by RadekManak** [comment]
javap is now available in GUI. Options support is finished only in the backend but it shouldn't be too difficult to add a text field to GUI and hook it up.
