### ISSUE TITLE
add way to return to initiall setup instructions

### ISSUE THREAD

**Issue by jandrlik** [pmikova/java-runtime-decompiler#28]
when you start your application for the first time, you can see something like initiall setup guide for the application. However it dissapears as soon as you click on some of the processes and you are unable to view the guide unless you restart the whole app. It would be nice to have a way to return to the guide.

**Comment by judovana** [comment]
yup. Showing it from help menu would be better then those two nothig doing  buttons:)

**Comment by RadekManak** [comment]
Actually, you can. If you hold CTRL and click on a VM you will deselect it and see the welcome screen. This is definitely an issue though.  As judovana said opening it from menubar -> help -> usage would be a solution but I would prefer Usage to be its own window.

**Comment by judovana** [comment]
works:D It is really coolly hidden feature :)))
