### ISSUE TITLE
confusing lines in guide

### ISSUE THREAD

**Issue by jandrlik** [pmikova/java-runtime-decompiler#29]
"Before you start using the application you need to select Agent and Decompiler paths.
Go to menubar -> config -> configure" 
these two lines of your initiall setup guide are quite confusing since agent path is already selected and therefore you dont need to select it. As a fresh user I tried to follow the instructions and had to reinstall the app as i couldnt find the original agent path.

**Comment by judovana** [comment]
In addition, "download decompiler like.." is also wrong , as current setup for decompilers is already doing this pretty well. You jus tneed yuser to point to this.

**Comment by AurumTheEnd** [comment]
The README changes in release 3.0.0 should cover these problems.
