### ISSUE TITLE
missing refresh button for processes

### ISSUE THREAD

**Issue by jandrlik** [pmikova/java-runtime-decompiler#30]
when you start a new java process it wont appear in "Local Processes" bar, so you have to restart the whole application in order to refresh the "Local Processes" bar.

**Comment by RadekManak** [comment]
The idea was to refresh VMs automatically as they start and exit. I have made some progress to get it working but refreshing VMs made the application a bit unstable so I disabled it for now. Button could be easily added as a compromise for now. If stuff breaks we will blame the user /s

**Comment by AurumTheEnd** [comment]
The VM list refreshes automatically since 329edaf7 and 450fdddd, the former one being added just a day after this thread. I'm guessing you just forgot to close this issue.
