### ISSUE TITLE
immutable custom plugin configurations

### ISSUE THREAD

**Issue by jandrlik** [pmikova/java-runtime-decompiler#31]
in "Plugin configuration" window upon creating a new custom configuration, you cant erase or edit it.

**Comment by RadekManak** [comment]
Are you running the latest version? I think I fixed that one. see #27

**Comment by judovana** [comment]
yes. this is not the same

**Comment by RadekManak** [comment]
I still can't reproduce the issue. Either provide more info or you're on your own.

**Comment by judovana** [comment]
in plugin configuration, just click to  "new"
New item without name appear in list (and is ..semi saved) but cant be edited nor deleted

**Comment by judovana** [comment]
hmm.. likely it is #27 and i had ovelrooked the commit is not in released jar.

**Comment by RadekManak** [comment]
Yeah, that commit is only available from git/copr at the moment. Closing as duplicate.
