### ISSUE TITLE
plugin configuration should have validate button

### ISSUE THREAD

**Issue by judovana** [pmikova/java-runtime-decompiler#32]
Validation of plugin is compelx process containing compilation. It should  be enabled to be lunched on demand, with all possible output message sin case of failure.

**Comment by AurumTheEnd** [comment]
Didn't this get added in [3d1a0d0](https://github.com/pmikova/java-runtime-decompiler/commit/3d1a0d0a7db6681e2fbd55ed3048c646945440d6)?
