### ISSUE TITLE
fix Lambdas

### ISSUE THREAD

**Issue by judovana** [pmikova/java-runtime-decompiler#38]
It looks like all classes containing Lambda word are excluded

public class LambdaPokus {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        new Thread(() -> {
            while (true) {
            }
        }).start();
    }

}

This class LambdaPokus is never listed by JRD, and used Lambda is also not listed

**Comment by RadekManak** [comment]
They are filtered out. 

DecompilerRequestReceiver. Line 220: 
```
        for (String s : list) {
            if (!(s.contains("Lambda") | s.startsWith("["))){
                list1.add(s);
            }
        }
```
They cause an exception in agent when you request their bytecode. I haven't looked into why yet.

**Comment by judovana** [comment]
I have added lsiting of lambdas, but sorted them to the end of list.
https://github.com/pmikova/java-runtime-decompiler/commits/master

**Comment by judovana** [comment]
https://github.com/pmikova/java-runtime-decompiler/commit/fd66fd3a37cc899b11d97a13e0e23319d86f39c3

**Comment by judovana** [comment]
can notbe fixed
