### ISSUE TITLE
fix doclint errors

### ISSUE THREAD

**Issue by judovana** [pmikova/java-runtime-decompiler#39]
Generating javadoc on upstream JDK 8+fails on doclint.
Note, jdk8 in fedora have doclint disabled

**Comment by judovana** [comment]
in addition, the monky emoticon  - https://src.fedoraproject.org/rpms/java-runtime-decompiler/c/d63f93c8d3697956a67d713bb848ac36c5cc7aec?branch=epel7 is not exactly nice :)

**Comment by RadekManak** [comment]
The monkey is gone on b. pm-refactor.

**Comment by judovana** [comment]
poor monkey:(

**Comment by judovana** [comment]
fixed for now.
