### ISSUE TITLE
Implement About dialog in menubar

### ISSUE THREAD

**Issue by RadekManak** [pmikova/java-runtime-decompiler#4]
Simple dialog window that shows version number, build information and a link to source.

**Comment by AurumTheEnd** [comment]
@RadekManak What did you mean by *build information*? The implementation of [78c4547](https://github.com/pmikova/java-runtime-decompiler/commit/78c4547bd14a1f5cd854f8345b922671573e5595) contains the version number, a link to the Github repo and a mention of the licence.
