### ISSUE TITLE
Incorrect popup position for overwrite class dialog

### ISSUE THREAD

**Issue by RadoslavCap** [pmikova/java-runtime-decompiler#60]
With multiple monitors is dialog for "Overwrite class" opened on most left monitor instead over the opened application. It would be nice to display it over the active window.

**Comment by AurumTheEnd** [comment]
That might just be because it's passing a null as its parent on creation.

**Comment by judovana** [comment]
The dialogs yes. But the main window itself ia also appearing where it should not. I woudl recommend to check https://github.com/AdoptOpenJDK/IcedTea-Web/blob/master/common/src/main/java/net/adoptopenjdk/icedteaweb/ui/swing/ScreenFinder.java for isnpiration.

Btw I did fedora release today. allw as good in your code.
