### ISSUE TITLE
org.terminusbrut missing

### ISSUE THREAD

**Issue by allex** [pmikova/java-runtime-decompiler#77]
[ERROR] Failed to execute goal on project runtime-decompiler: Could not resolve dependencies for project java-runtime-decompiler:runtime-decompiler:jar:4.0.0-SNAPSHOT: Failure to find org.terminusbrut:classpathless-compiler:jar:1.0-SNAPSHOT

**Comment by judovana** [comment]
Hello!

yes, you have to clone and ```mvn install``` https://github.com/mkoncek/classpathless-compiler to your locall maven repository (right now very simple project, no issues expected during build)
I'm going to fix this issue once  we proceed with 5.0 which is now a bit stuck.

Sorry for inconvinience

**Comment by judovana** [comment]
Also I'm not sure if the installed jasm &comp are properly downloaded. If not, they are built from here: https://github.com/openjdk/asmtools

This also have to be fixed for 5.0

**Comment by judovana** [comment]
All depnendencies should now be in maven central.

**Comment by mkoncek** [comment]
As of commit 384252cecca66f36707e3a47b55756c044513d9a this should no longer be an issue.
