### ISSUE TITLE
improve docs

### ISSUE THREAD

**Issue by judovana** [pmikova/java-runtime-decompiler#9]
There is no hint how to run built application:

 java -cp /usr/lib/jvm/java-1.8.0-openjdk/lib/tools.jar:java-runtime-decompiler-1.0.0-SNAPSHOT.jar:/home/jvanek/.m2/repository/com/fifesoft/rsyntaxtextarea/2.6.1/rsyntaxtextarea-2.6.1.jar:/home/jvanek/.m2/repository/org/jboss/byteman/byteman/3.0.5/byteman-3.0.5.jar::/home/jvanek/.m2/repository/org/jboss/byteman/byteman-install/3.0.5/byteman-install-3.0.5.jar::/home/jvanek/.m2/repository/org/jboss/byteman/byteman-submit/3.0.5/byteman-submit-3.0.5.jar  com.redhat.thermostat.vm.decompiler.data.Main

Window opens, but :
Error opening zip file or JAR manifest missing: null
Classes couldn't be loaded
Classes couldn't be loaded
And no classes loaded, nor opened.

Is the only output I had.  Am I missing some classpath? Or other issue? 
If better readme is not enough, then maybe  maven assembly?

Lookng forward for first release!

**Comment by RadekManak** [comment]
Yeah, the documentation is currently nonexistent and error messages are sometimes misleading.

If the application window opened for you and attaching to VM doesn't work that probably means you forgot/didn't know you have to configure the path to agent and external decompiler of your choice. (Currently, Procyon is the only one we tested that works).

To get it to work you need to select config -> configure at the top menubar and fill the paths.

You can get the agent here:
https://github.com/pmikova/thermostat-decompiler-agent
And Procyon decompiler here:
https://bitbucket.org/mstrobel/procyon/downloads/

I'll try to make at least some basic docs and fix the misleading welcome screen tomorrow.

**Comment by AurumTheEnd** [comment]
Since documentation is now in a much better state and we now have launcher scripts, I'll be closing this issue as it's outdated.
